Added image to readme
thoughtindustries/helium pull request #162
Opened 2022-09-16 15:14 UTC by jackanticoti

Added image to readme

2022-09-16 15:16 UTC, chrisvariety requested changes
`.DS_Store` files should not be committed -- can add that to `.gitignore`.

2022-09-16 15:16 UTC, chrisvariety commented on README.md
> +    <a href="https://developer.thoughtindustries.com/build/developer-guide/"><img src="./.github/images/helium_logo.png" alt="Hydrogen Logo"/></a>
Helium

2022-10-14 15:00 UTC, jackanticoti commented
I believe I removed the .DS_store from .github

2022-10-14 15:01 UTC, chrisvariety approved these changes

2022-10-14 15:17 UTC, merged